name: on-push

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

  unit-tests:
    name: unit-tests (3.10)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ubuntu-latest-3.10
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        mamba-version: '*'
        python-version: '3.10'
        environment-file: environment.yml
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run tests
      run: |
        make test

  type-check:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ubuntu-latest-3.10
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        mamba-version: '*'
        python-version: '3.10'
        environment-file: environment.yml
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run code quality checks
      run: |
        make type-check

  integration-tests:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        include:
        - python-version: '3.10'
          extra: -minver

    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ubuntu-latest-${{ matrix.python-version }}${{ matrix.extra }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        mamba-version: '*'
        python-version: ${{ matrix.python-version }}
        environment-file: environment${{ matrix.extra }}.yml
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run tests
      run: |
        make test

  distribution:
    runs-on: ubuntu-latest
    needs: [integration-tests, type-check]

    steps:
    - uses: actions/checkout@v3
    - name: Build distributions
      run: |
        $CONDA/bin/python -m pip install build
        $CONDA/bin/python -m build
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
